BTCPayServer/Controllers/PullPaymentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Abstractions.Models;
using BTCPayServer.Client.Models;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.Models;
using BTCPayServer.Payments;
using BTCPayServer.Services;
using BTCPayServer.Services.Rates;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BTCPayServer.Controllers
{
    [AllowAnonymous]
    public class PullPaymentController : Controller
    {
        private readonly ApplicationDbContextFactory _dbContextFactory;
        private readonly BTCPayNetworkProvider _networkProvider;
        private readonly CurrencyNameTable _currencyNameTable;
        private readonly PullPaymentHostedService _pullPaymentHostedService;
        private readonly BTCPayNetworkJsonSerializerSettings _serializerSettings;
        private readonly IEnumerable<IPayoutHandler> _payoutHandlers;

        public PullPaymentController(ApplicationDbContextFactory dbContextFactory,
            BTCPayNetworkProvider networkProvider,
            CurrencyNameTable currencyNameTable,
            PullPaymentHostedService pullPaymentHostedService,
            BTCPayNetworkJsonSerializerSettings serializerSettings,
            IEnumerable<IPayoutHandler> payoutHandlers)
        {
            _dbContextFactory = dbContextFactory;
            _networkProvider = networkProvider;
            _currencyNameTable = currencyNameTable;
            _pullPaymentHostedService = pullPaymentHostedService;
            _serializerSettings = serializerSettings;
            _payoutHandlers = payoutHandlers;
        }

        [Route("pull-payments/{pullPaymentId}")]
        public async Task<IActionResult> ViewPullPayment(string pullPaymentId)
        {
            using var ctx = _dbContextFactory.CreateContext();
            var pp = await ctx.PullPayments.FindAsync(pullPaymentId);
            if (pp is null)
                return NotFound();

            var blob = pp.GetBlob();
            var payouts = (await ctx.Payouts.GetPayoutInPeriod(pp)
                                           .OrderByDescending(o => o.Date)
                                           .ToListAsync())
                           .Select(o => new
                           {
                               Entity = o,
                               Blob = o.GetBlob(_serializerSettings),
                               ProofBlob = _payoutHandlers.FindPayoutHandler(o.GetPaymentMethodId())?.ParseProof(o)
                           });
            var cd = _currencyNameTable.GetCurrencyData(blob.Currency, false);
            var totalPaid = payouts.Where(p => p.Entity.State != PayoutState.Cancelled).Select(p => p.Blob.Amount).Sum();
            var amountDue = blob.Limit - totalPaid;

            ViewPullPaymentModel vm = new ViewPullPaymentModel(pp, DateTimeOffset.UtcNow)
            {
                AmountFormatted = _currencyNameTable.FormatCurrency(blob.Limit, blob.Currency),
                AmountCollected = totalPaid,
                AmountCollectedFormatted = _currencyNameTable.FormatCurrency(totalPaid, blob.Currency),
                AmountDue = amountDue,
                ClaimedAmount = amountDue,
                AmountDueFormatted = _currencyNameTable.FormatCurrency(amountDue, blob.Currency),
                CurrencyData = cd,
                StartDate = pp.StartDate,
                LastRefreshed = DateTime.UtcNow,
                Payouts = payouts
                          .Select(entity => new ViewPullPaymentModel.PayoutLine
                          {
                              Id = entity.Entity.Id,
                              Amount = entity.Blob.Amount,
                              AmountFormatted = _currencyNameTable.FormatCurrency(entity.Blob.Amount, blob.Currency),
                              Currency = blob.Currency,
                              Status = entity.Entity.State,
                              Destination = entity.Blob.Destination,
                              PaymentMethod = PaymentMethodId.Parse(entity.Entity.PaymentMethodId),
                              Link = entity.ProofBlob?.Link,
                              TransactionId = entity.ProofBlob?.Id
                          }).ToList()
            };
            vm.IsPending &= vm.AmountDue > 0.0m;
            return View(nameof(ViewPullPayment), vm);
        }

        [Route("pull-payments/{pullPaymentId}/claim")]
        [HttpPost]
        public async Task<IActionResult> ClaimPullPayment(string pullPaymentId, ViewPullPaymentModel vm)
        {
            using var ctx = _dbContextFactory.CreateContext();
            var pp = await ctx.PullPayments.FindAsync(pullPaymentId);
            if (pp is null)
            {
                ModelState.AddModelError(nameof(pullPaymentId), "This pull payment does not exists");
            }

            var ppBlob = pp.GetBlob();

            var paymentMethodId = ppBlob.SupportedPaymentMethods.FirstOrDefault(id => vm.SelectedPaymentMethod == id.ToString());

            var payoutHandler = paymentMethodId is null ? null : _payoutHandlers.FindPayoutHandler(paymentMethodId);
            if (payoutHandler is null)
            {
                ModelState.AddModelError(nameof(vm.SelectedPaymentMethod), $"Invalid destination with selected payment method");
                return await ViewPullPayment(pullPaymentId);
            }
            var destination = await payoutHandler?.ParseClaimDestination(paymentMethodId, vm.Destination, true);
            if (destination.destination is null)
            {
                ModelState.AddModelError(nameof(vm.Destination), destination.error ?? "Invalid destination with selected payment method");
                return await ViewPullPayment(pullPaymentId);
            }

            if (vm.ClaimedAmount == 0)
            {
                ModelState.AddModelError(nameof(vm.ClaimedAmount),
                    $"Amount is required");
            }
            else if (vm.ClaimedAmount != 0 && destination.destination.Amount != null && vm.ClaimedAmount != destination.destination.Amount)
            {
                ModelState.AddModelError(nameof(vm.ClaimedAmount),
                    $"Amount is implied in destination ({destination.destination.Amount}) that does not match the payout amount provided {vm.ClaimedAmount})");
            }

            if (!ModelState.IsValid)
            {
                return await ViewPullPayment(pullPaymentId);
            }

            var result = await _pullPaymentHostedService.Claim(new ClaimRequest()
            {
                Destination = destination.destination,
                PullPaymentId = pullPaymentId,
                Value = vm.ClaimedAmount,
                PaymentMethodId = paymentMethodId
            });

            if (result.Result != ClaimRequest.ClaimResult.Ok)
            {
                if (result.Result == ClaimRequest.ClaimResult.AmountTooLow)
                {
                    ModelState.AddModelError(nameof(vm.ClaimedAmount), ClaimRequest.GetErrorMessage(result.Result));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ClaimRequest.GetErrorMessage(result.Result));
                }
                return await ViewPullPayment(pullPaymentId);
            }
            else
            {
                TempData.SetStatusMessageModel(new StatusMessageModel()
                {
                    Message = $"Your claim request of {_currencyNameTable.DisplayFormatCurrency(vm.ClaimedAmount, ppBlob.Currency)} to {vm.Destination} has been submitted and is awaiting approval.",
                    Severity = StatusMessageModel.StatusSeverity.Success
                });
            }
            return RedirectToAction(nameof(ViewPullPayment), new { pullPaymentId = pullPaymentId });
        }
    }
}

BTCPayServer/Views/StorePullPayments/NewPullPayment.cshtml
@using BTCPayServer.Abstractions.Extensions
@using BTCPayServer.Views.Stores
@model BTCPayServer.Models.WalletViewModels.NewPullPaymentModel
@{
    ViewData.SetActivePage(StoreNavPages.PullPayments, "New pull payment", Context.GetStoreData().Id);
}

<partial name="_StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <h2 class="mb-3">@ViewData["Title"]</h2>

        <form method="post"
              asp-route-walletId="@Context.GetRouteValue("walletId")"
              asp-action="NewPullPayment">
            <div class="form-group">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group col-8">
                    <label asp-for="Amount" class="form-label"></label>
                    <input asp-for="Amount" class="form-control"/>
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Currency" class="form-label"></label>
                    <input asp-for="Currency" class="form-control"/>
                    <span asp-validation-for="Currency" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mb-4">
                <label asp-for="PaymentMethods" class="form-label"></label>
                @foreach (var item in Model.PaymentMethodItems)
                {
                    <div class="form-check mb-2">
                        <label class="form-label">
                            <input name="PaymentMethods" class="form-check-input" type="checkbox" value="@item.Value" @(item.Selected ? "checked" : "")>
                            @item.Text
                        </label>
                    </div>
                }
                <span asp-validation-for="PaymentMethods" class="text-danger mt-0"></span>
            </div>

            <h5 class="mt-4 mb-2">Additional Options</h5>
            <div class="form-group">
                <div class="accordion" id="additional">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="additional-custom-css-header">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#additional-custom-css" aria-expanded="false" aria-controls="additional-custom-css">
                                Custom CSS
                                <vc:icon symbol="caret-down"/>
                            </button>
                        </h2>
                        <div id="additional-custom-css" class="accordion-collapse collapse" aria-labelledby="additional-custom-css-header">
                            <div class="accordion-body">
                                <div class="form-group">
                                    <label asp-for="CustomCSSLink" class="form-label"></label>
                                    <a href="https://docs.btcpayserver.org/Development/Theme/#2-bootstrap-themes" target="_blank" rel="noreferrer noopener">
                                        <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
                                    </a>
                                    <input asp-for="CustomCSSLink" class="form-control"/>
                                    <span asp-validation-for="CustomCSSLink" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EmbeddedCSS" class="form-label"></label>
                                    <textarea asp-for="EmbeddedCSS" rows="10" cols="40" class="form-control"></textarea>
                                    <span asp-validation-for="EmbeddedCSS" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="Create"/>
            </div>
        </form>
    </div>
</div>

BTCPayServer/Views/StorePullPayments/Payouts.cshtml
@using BTCPayServer.Client.Models
@using BTCPayServer.Payments
@using BTCPayServer.Views.Stores
@using BTCPayServer.Abstractions.Extensions
@using BTCPayServer.Client
@model BTCPayServer.Models.WalletViewModels.PayoutsModel

@inject IEnumerable<IPayoutHandler> PayoutHandlers;
@{
    ViewData.SetActivePage(StoreNavPages.Payouts, $"Payouts{(string.IsNullOrEmpty(Model.PullPaymentName) ? string.Empty : " for pull payment " + Model.PullPaymentName)}", Context.GetStoreData().Id);
    Model.PaginationQuery ??= new Dictionary<string, object>();
    Model.PaginationQuery.Add("pullPaymentId", Model.PullPaymentId);
    Model.PaginationQuery.Add("paymentMethodId", Model.PaymentMethodId);
    Model.PaginationQuery.Add("payoutState", Model.PayoutState);
    var stateActions = new List<(string Action, string Text)>();
    if (PaymentMethodId.TryParse(Model.PaymentMethodId, out var paymentMethodId))
    {
        var payoutHandler = PayoutHandlers.FindPayoutHandler(paymentMethodId);
        if (payoutHandler is null)
            return;
        stateActions.AddRange(payoutHandler.GetPayoutSpecificActions().Where(pair => pair.Key == Model.PayoutState).SelectMany(pair => pair.Value));
        
    }
    switch (Model.PayoutState)
    {
        case PayoutState.AwaitingApproval:
            stateActions.Add(("approve", "Approve selected payouts"));
            stateActions.Add(("approve-pay", "Approve & Send selected payouts"));
            stateActions.Add(("cancel", "Cancel selected payouts"));
            break;
        case PayoutState.AwaitingPayment:
            stateActions.Add(("pay", "Send selected payouts"));
            stateActions.Add(("cancel", "Cancel selected payouts"));
            stateActions.Add(("mark-paid", "Mark selected payouts as already paid"));
            break;
    }
    
}

@section PageFootContent {
    <script>
        delegate('click', '.selectAll', e => {
            const { payoutState } = e.target.dataset;
            document.querySelectorAll(`.selection-item-${payoutState}`).forEach(checkbox => {
                checkbox.checked = e.target.checked;
            });
        });
    </script>
}

<partial name="_StatusMessage" />

<h2 class="mt-1 mb-4">@ViewData["Title"]</h2>

<form method="post">
    <input type="hidden" asp-for="PaymentMethodId"/>
    <input type="hidden" asp-for="PayoutState"/>
    <div class="row">
        <div class="col-12">
            <ul class="nav nav-pills  bg-tile mb-2" style="border-radius:4px; border: 1px solid var(--btcpay-body-border-medium)">
                @foreach (var state in Model.PaymentMethods)
                {
                    <li class="nav-item py-0">
                        <a asp-action="Payouts" asp-route-storeId="@Context.GetRouteValue("storeId")"
                           asp-route-payoutState="@Model.PayoutState"
                           asp-route-paymentMethodId="@state.ToString()"
                           asp-route-pullPaymentId="@Model.PullPaymentId"
                           class="nav-link me-1 @(state.ToString() == Model.PaymentMethodId ? "active" : "")"
                           id="@state.ToString()-view"
                           role="tab">
                            @state.ToPrettyString()
                        </a>
                    </li>
                }
            </ul>
            <ul class="nav nav-pills  bg-tile mb-2" style="border: 1px solid var(--btcpay-body-border-medium)">
                @foreach (var state in Model.PayoutStateCount)
                {
                    <li class="nav-item py-0">
                        <a id="@state.Key-view" 
                           asp-action="Payouts" 
                           asp-route-storeId="@Context.GetRouteValue("storeId")" 
                           asp-route-payoutState="@state.Key" 
                           asp-route-pullPaymentId="@Model.PullPaymentId" 
                           asp-route-paymentMethodId="@Model.PaymentMethodId"
                           class="nav-link me-1 @(state.Key == Model.PayoutState ? "active" : "")" role="tab">@state.Key.GetStateString() (@state.Value)</a>
                    </li>
                }
            </ul>
           
        </div>
        @if (Model.Payouts.Any() && stateActions.Any())
        {
            <div class="col-12" permission="@Policies.CanModifyStoreSettings">
                <div class="dropdown  mt-4 ms-xl-auto mt-xl-0">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" id="@Model.PayoutState-actions">
                                    Actions
                                </button>
                                <div class="dropdown-menu" aria-labelledby="@Model.PayoutState-actions">
                                    @foreach (var action in stateActions)
                                    {
                                        <button type="submit" id="@Model.PayoutState-@action.Action" name="Command" class="dropdown-item" role="button" value="@Model.PayoutState-@action.Action">@action.Text</button>
                                    }
                                </div>
                            </div>
            </div>
            
        }
    </div>

    <div class="row">

            @if (Model.Payouts.Any())
            {
                <table class="table table-hover table-responsive-lg">
                    <thead class="thead-inverse">
                    <tr>
                        <th permission="@Policies.CanModifyStoreSettings">
                            <input id="@Model.PayoutState-selectAllCheckbox" type="checkbox" class="form-check-input selectAll" data-payout-state="@Model.PayoutState.ToString()" />
                        </th>
                        <th style="min-width: 90px;" class="col-md-auto">
                            Date
                        </th>
                        <th class="text-start">Source</th>
                        <th class="text-start">Destination</th>
                        <th class="text-end">Amount</th>
                        @if (Model.PayoutState != PayoutState.AwaitingApproval)
                        {
                            <th class="text-end">Transaction</th>
                        }
                    </tr>
                    </thead>
                    <tbody>
                    @for (int i = 0; i < Model.Payouts.Count; i++)
                    {
                        var pp = Model.Payouts[i];
                        <tr class="payout">
                            <td permission="@Policies.CanModifyStoreSettings">
                                <span>
                                    <input type="checkbox" class="selection-item-@Model.PayoutState.ToString() form-check-input" asp-for="Payouts[i].Selected"/>
                                    <input type="hidden" asp-for="Payouts[i].PayoutId"/>
                                </span>
                            </td>
                            <td>
                                <span>@pp.Date.ToBrowserDate()</span>
                            </td>
                            <td class="mw-100">
                                <span>@pp.PullPaymentName</span>
                            </td>
                            <td  title="@pp.Destination">
                                <span class="text-break">@pp.Destination</span>
                            </td>
                            <td class="text-end">
                                <span>@pp.Amount</span>
                            </td>
                            @if (Model.PayoutState != PayoutState.AwaitingApproval)
                            {
                                <td class="text-end">
                                    @if (!(pp.ProofLink is null))
                                    {
                                        <a class="transaction-link" href="@pp.ProofLink" rel="noreferrer noopener">Link</a>
                                    }
                                </td>
                            }
                        </tr>
                    }
                    </tbody>
                </table>
            }
            else
            {
                <p class="mb-0 py-4" id="@Model.PayoutState-no-payouts">There are no payouts matching this criteria.</p>
            }
        <vc:pager view-model="Model"/>
    </div>
</form>

BTCPayServer/Views/StorePullPayments/PullPayments.cshtml
@using BTCPayServer.Views.Stores
@using BTCPayServer.Abstractions.Extensions
@using BTCPayServer.Client
@model BTCPayServer.Models.WalletViewModels.PullPaymentsModel
@{
    ViewData.SetActivePage(StoreNavPages.PullPayments, "Pull payments", Context.GetStoreData().Id);
    var nextStartDateSortOrder = (string)ViewData["NextStartSortOrder"];
    string startDateSortOrder = null;
    switch (nextStartDateSortOrder)
    {
        case "asc":
            startDateSortOrder = "desc";
            break;
        case "desc":
            startDateSortOrder = "asc";
            break;
    }

    var sortIconClass = "fa-sort";
    if (startDateSortOrder != null)
    {
        sortIconClass = $"fa-sort-alpha-{startDateSortOrder}";
    }

    var sortByDesc = "Sort by descending...";
    var sortByAsc = "Sort by ascending...";
}

@section PageHeadContent {
    <style type="text/css">
        .tooltip-inner {
            text-align: left;
        }
    </style>
}

<partial name="_StatusMessage" />

<div class="d-flex align-items-center justify-content-between mb-2">
    <h2 class="mb-0">
        @ViewData["Title"]
        <small>
            <a href="https://docs.btcpayserver.org/PullPayments/" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
        </small>
    </h2>
    <a permission="@Policies.CanModifyStoreSettings" asp-action="NewPullPayment" asp-route-storeId="@Context.GetRouteValue("storeId")" class="btn btn-primary" role="button" id="NewPullPayment">
        <span class="fa fa-plus"></span> Create Pull Payment
    </a>
</div>

@if (Model.PullPayments.Any())
{
    <div class="row">
        @foreach (var pp in Model.PullPayments)
        {
            <script id="tooptip_template_@pp.Id" type="text/template">
                <span>Awaiting:&nbsp;<span class="float-end">@pp.Progress.Awaiting</span></span>
                <br />
                <span>Completed:&nbsp;<span class="float-end">@pp.Progress.Completed</span></span>
                <br />
                <span>Limit:&nbsp;<span class="float-end">@pp.Progress.Limit</span></span>
                @if (pp.Progress.ResetIn != null)
                {
                    <br />
                    <span>Resets in:&nbsp;<span class="float-end">@pp.Progress.ResetIn</span></span>
                }
                @if (pp.Progress.EndIn != null)
                {
                    <br />
                    <span>Expires in:&nbsp;<span class="float-end">@pp.Progress.EndIn</span></span>
                }
            </script>
        }
        <div class="col-md-12">
            <table class="table table-hover table-responsive-lg">
                <thead class="thead-inverse">
                <tr>
                    <th scope="col">
                        <a
                            asp-action="PullPayments"
                            asp-route-sortOrder="@(nextStartDateSortOrder ?? "asc")"
                            class="text-nowrap"
                            title="@(nextStartDateSortOrder == "desc" ? sortByAsc : sortByDesc)">
                            Start
                            <span class="fa @(sortIconClass)"></span>
                        </a>
                    </th>
                    <th scope="col">Name</th>
                    <th scope="col">Refunded</th>
                    <th scope="col" class="text-end" >Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var pp in Model.PullPayments)
                {
                    <tr>
                        <td>@pp.StartDate.ToBrowserDate()</td>
                        <td>@pp.Name</td>
                        <td class="align-middle">
                            <div class="progress ppProgress" data-pp="@pp.Id" data-bs-toggle="tooltip" data-bs-html="true">
                                <div class="progress-bar" role="progressbar" aria-valuenow="@pp.Progress.CompletedPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width:@(pp.Progress.CompletedPercent)%;">
                                </div>
                                <div class="progress-bar" role="progressbar" aria-valuenow="@pp.Progress.AwaitingPercent"
                                     aria-valuemin="0" aria-valuemax="100" style="background-color:orange; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width:@(pp.Progress.AwaitingPercent)%;">
                                </div>
                            </div>
                        </td>
                        <td class="text-end">
                            <a asp-action="ViewPullPayment"
                               asp-controller="PullPayment"
                               asp-route-pullPaymentId="@pp.Id">
                                View
                            </a> -
                            <a class="pp-payout"
                               asp-action="Payouts"
                               asp-route-storeId="@Context.GetRouteValue("storeId")"
                               asp-route-pullPaymentId="@pp.Id">
                                Payouts
                            </a>
                            <span permission="@Policies.CanModifyStoreSettings"> - </span>
                            <a asp-action="ArchivePullPayment"
                               permission="@Policies.CanModifyStoreSettings" 
                               asp-route-storeId="@Context.GetRouteValue("storeId")"
                               asp-route-pullPaymentId="@pp.Id"
                               data-bs-toggle="modal"
                               data-bs-target="#ConfirmModal"
                               data-description="Do you really want to archive the pull payment <strong>@pp.Name</strong>?">
                                Archive
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>

        </div>
        <vc:pager view-model="Model"/>
    </div>

    <partial name="_Confirm" model="@(new ConfirmModel("Archive pull payment", "Do you really want to archive the pull payment?", "Archive"))"/>

@section PageFootContent {
    <script>
            var ppProgresses = document.getElementsByClassName("ppProgress");
            for (var i = 0; i < ppProgresses.length; i++) {
                var pp = ppProgresses[i];
                var ppId = pp.getAttribute("data-pp");
                var template = document.getElementById("tooptip_template_" + ppId);
                pp.setAttribute("title", template.innerHTML);
            }
        </script>
}
}
else
{
    <p class="text-secondary mt-3">
        There are no pull payments yet.
    </p>
}