BTCPayServer/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Client;
using BTCPayServer.Configuration;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.Models;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Payments;
using BTCPayServer.Payments.Lightning;
using BTCPayServer.Rating;
using BTCPayServer.Security.Bitpay;
using BTCPayServer.Services;
using BTCPayServer.Services.Apps;
using BTCPayServer.Services.Invoices;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NBitcoin;
using NBitcoin.DataEncoders;
using StoreData = BTCPayServer.Data.StoreData;

namespace BTCPayServer.Controllers
{
    [Route("stores")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    [Authorize(Policy = Policies.CanModifyStoreSettings, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    [AutoValidateAntiforgeryToken]
    public partial class StoresController : Controller
    {
        readonly RateFetcher _RateFactory;
        public string CreatedStoreId { get; set; }
        public StoresController(
            IServiceProvider serviceProvider,
            BTCPayServerOptions btcpayServerOptions,
            BTCPayServerEnvironment btcpayEnv,
            StoreRepository repo,
            TokenRepository tokenRepo,
            UserManager<ApplicationUser> userManager,
            AccessTokenController tokenController,
            BTCPayWalletProvider walletProvider,
            BTCPayNetworkProvider networkProvider,
            RateFetcher rateFactory,
            ExplorerClientProvider explorerProvider,
            LanguageService langService,
            PaymentMethodHandlerDictionary paymentMethodHandlerDictionary,
            SettingsRepository settingsRepository,
            IAuthorizationService authorizationService,
            EventAggregator eventAggregator,
            AppService appService,
            WebhookNotificationManager webhookNotificationManager,
            IDataProtectionProvider dataProtector,
            NBXplorerDashboard Dashboard)
        {
            _RateFactory = rateFactory;
            _Repo = repo;
            _TokenRepository = tokenRepo;
            _UserManager = userManager;
            _LangService = langService;
            _TokenController = tokenController;
            _WalletProvider = walletProvider;
            _paymentMethodHandlerDictionary = paymentMethodHandlerDictionary;
            _settingsRepository = settingsRepository;
            _authorizationService = authorizationService;
            _appService = appService;
            DataProtector = dataProtector.CreateProtector("ConfigProtector");
            WebhookNotificationManager = webhookNotificationManager;
            _EventAggregator = eventAggregator;
            _NetworkProvider = networkProvider;
            _ExplorerProvider = explorerProvider;
            _ServiceProvider = serviceProvider;
            _BtcpayServerOptions = btcpayServerOptions;
            _BTCPayEnv = btcpayEnv;
            _Dashboard = Dashboard;
        }

        readonly BTCPayServerOptions _BtcpayServerOptions;
        readonly BTCPayServerEnvironment _BTCPayEnv;
        readonly IServiceProvider _ServiceProvider;
        readonly BTCPayNetworkProvider _NetworkProvider;
        private readonly ExplorerClientProvider _ExplorerProvider;
        readonly BTCPayWalletProvider _WalletProvider;
        readonly AccessTokenController _TokenController;
        readonly StoreRepository _Repo;
        readonly TokenRepository _TokenRepository;
        readonly UserManager<ApplicationUser> _UserManager;
        private readonly LanguageService _LangService;
        private readonly PaymentMethodHandlerDictionary _paymentMethodHandlerDictionary;
        private readonly SettingsRepository _settingsRepository;
        private readonly IAuthorizationService _authorizationService;
        private readonly AppService _appService;
        private readonly EventAggregator _EventAggregator;
        private readonly NBXplorerDashboard _Dashboard;

        [TempData]
        public bool StoreNotConfigured
        {
            get; set;
        }

        [HttpGet]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers()
        {
            StoreUsersViewModel vm = new StoreUsersViewModel();
            await FillUsers(vm);
            return View(vm);
        }

        private async Task FillUsers(StoreUsersViewModel vm)
        {
            var users = await _Repo.GetStoreUsers(CurrentStore.Id);
            vm.StoreId = CurrentStore.Id;
            vm.Users = users.Select(u => new StoreUsersViewModel.StoreUserViewModel()
            {
                Email = u.Email,
                Id = u.Id,
                Role = u.Role
            }).ToList();
        }

        public StoreData CurrentStore
        {
            get
            {
                return this.HttpContext.GetStoreData();
            }
        }

        [HttpPost]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers(StoreUsersViewModel vm)
        {
            await FillUsers(vm);
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var user = await _UserManager.FindByEmailAsync(vm.Email);
            if (user == null)
            {
                ModelState.AddModelError(nameof(vm.Email), "User not found");
                return View(vm);
            }
            if (!StoreRoles.AllRoles.Contains(vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Role), "Invalid role");
                return View(vm);
            }
            if (!await _Repo.AddStoreUser(CurrentStore.Id, user.Id, vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Email), "The user already has access to this store");
                return View(vm);
            }
            TempData[WellKnownTempData.SuccessMessage] = "User added successfully.";
            return RedirectToAction(nameof(StoreUsers));
        }

        [HttpGet("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUser(string userId)
        {
            var user = await _UserManager.FindByIdAsync(userId);
            if (user == null)
                return NotFound();
            return View("Confirm", new ConfirmModel("Remove store user", $"This action will prevent <strong>{user.Email}</strong> from accessing this store and its settings. Are you sure?", "Remove"));
        }

        [HttpPost("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUserPost(string storeId, string userId)
        {
            await _Repo.RemoveStoreUser(storeId, userId);
            TempData[WellKnownTempData.SuccessMessage] = "User removed successfully.";
            return RedirectToAction(nameof(StoreUsers), new { storeId, userId });
        }

        [HttpGet("{storeId}/rates")]
        public IActionResult Rates()
        {
            var exchanges = GetSupportedExchanges();
            var storeBlob = CurrentStore.GetStoreBlob();
            var vm = new RatesViewModel();
            vm.SetExchangeRates(exchanges, storeBlob.PreferredExchange ?? CoinGeckoRateProvider.CoinGeckoName);
            vm.Spread = (double)(storeBlob.Spread * 100m);
            vm.StoreId = CurrentStore.Id;
            vm.Script = storeBlob.GetRateRules(_NetworkProvider).ToString();
            vm.DefaultScript = storeBlob.GetDefaultRateRules(_NetworkProvider).ToString();
            vm.AvailableExchanges = exchanges;
            vm.DefaultCurrencyPairs = storeBlob.GetDefaultCurrencyPairString();
            vm.ShowScripting = storeBlob.RateScripting;
            return View(vm);
        }

        [HttpPost("{storeId}/rates")]
        public async Task<IActionResult> Rates(RatesViewModel model, string command = null, string storeId = null, CancellationToken cancellationToken = default)
        {
            if (command == "scripting-on")
            {
                return RedirectToAction(nameof(ShowRateRules), new { scripting = true, storeId = model.StoreId });
            }
            else if (command == "scripting-off")
            {
                return RedirectToAction(nameof(ShowRateRules), new { scripting = false, storeId = model.StoreId });
            }

            var exchanges = GetSupportedExchanges();
            model.SetExchangeRates(exchanges, model.PreferredExchange);
            model.StoreId = storeId ?? model.StoreId;
            CurrencyPair[] currencyPairs = null;
            try
            {
                currencyPairs = model.DefaultCurrencyPairs?
                     .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                     .Select(p => CurrencyPair.Parse(p))
                     .ToArray();
            }
            catch
            {
                ModelState.AddModelError(nameof(model.DefaultCurrencyPairs), "Invalid currency pairs (should be for example: BTC_USD,BTC_CAD,BTC_JPY)");
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.PreferredExchange != null)
                model.PreferredExchange = model.PreferredExchange.Trim().ToLowerInvariant();

            var blob = CurrentStore.GetStoreBlob();
            model.DefaultScript = blob.GetDefaultRateRules(_NetworkProvider).ToString();
            model.AvailableExchanges = exchanges;

            blob.PreferredExchange = model.PreferredExchange;

BTCPayServer/Views/Shared/CameraScanner.cshtml
@inject BTCPayServer.Security.ContentSecurityPolicies csp
@{
    csp.Add("worker-src", "blob:");
}

<template id="camera-qr-scanner-wrap">
	<div v-if="modalId" :id="modalId" class="modal fade" data-bs-backdrop="static">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
                    <h5 class="modal-title">
                        {{title}}
                        <span v-if="workload.length > 0">Animated QR detected: {{workload.length}} / {{workload[0].total}} scanned</span>
                        <span v-if="decoder">Animated QR detected: {{decoder.processedPartsCount()}} / {{decoder.expectedPartCount()}} scanned</span>
                    </h5>
                    <button type="button" class="btn-close" aria-label="Close" v-on:click="close">
                        <vc:icon symbol="close"/>
                    </button>
				</div>
				<div class="modal-body">
					<slot/>
				</div>
			</div>
		</div>
	</div>
	<div v-else>
		<slot></slot>
		<div v-if="workload.length > 0">Animated QR detected: {{workload.length}} / {{workload[0].total}} scanned</div>
	</div>
</template>

<div id="camera-qr-scanner-modal-app" v-cloak class="only-for-js">
    <scanner-wrap v-bind="$data" v-on:close="close">
        <div  class="d-flex justify-content-center align-items-center" :class="{'border border-secondary': !isModal}">
            <div class="spinner-border text-secondary position-absolute" role="status"></div>
            <qrcode-drop-zone v-on:decode="onDecode" v-on:init="logErrors">
                <qrcode-stream v-on:decode="onDecode" v-on:init="onInit" :camera="cameraOff? 'off': cameras[camera]" :device-id="cameras[camera]" :track="paint"/>
            </qrcode-drop-zone>
            <qrcode-capture v-if="noStreamApiSupport" v-on:decode="onDecode" :camera="cameraOff? 'off': cameras[camera]" :device-id="cameras[camera]"/>
            
        </div>
        <div v-if="isLoaded && requestInput && cameras.length > 2" class="d-flex justify-content-center align-items-center mt-3">
            <button class="btn btn-secondary text-center" v-on:click="nextCamera">Switch camera</button>
        </div>
        <div v-else-if="qrData || errorMessage">
            <div v-if="errorMessage" class="alert alert-danger" role="alert">
                {{errorMessage}}
            </div>
            <div v-if="qrData" class="font-monospace mt-3" style="overflow:hidden;text-overflow:ellipsis;">
                {{qrData}}
            </div>
            <div class="mt-3">
                <button type="button" class="btn btn-primary me-1" v-if="qrData" v-on:click="submitData">Submit</button>
                <button type="button" class="btn btn-secondary me-1" v-on:click="retry">Retry</button>
                <button type="button" class="btn btn-outline-secondary" v-if="isModal" v-on:click="close">Cancel</button>
            </div>
        </div>
    </scanner-wrap>
</div>

<script>
function initCameraScanningApp(title, onDataSubmit, modalId) {
	const isModal = !!modalId;

	Vue.component('scanner-wrap', {
		props: ["modalId", "title", "workload", "decoder"],
		template: "#camera-qr-scanner-wrap",
		methods: {
			close() {
				this.$emit('close');
			}
		}
  	});

    const app = new Vue({
		el: '#camera-qr-scanner-modal-app',
		data() {
			return {
				isModal,
				isLoaded: !isModal,
				title: title,
				modalId: modalId,
				noStreamApiSupport: false,
				qrData: null,
				errorMessage: null,
				workload: [],
				camera: 0,
				cameraOff: true,
				cameras: ["auto"],
				decoder: null
			}
		},
		mounted() {
			if (this.isModal) {
				const modal = document.getElementById(this.modalId);
				modal.addEventListener('shown.bs.modal', () => { this.isLoaded = true; this.cameraOff = false; });
				modal.addEventListener('hide.bs.modal', () => { this.isLoaded = false; this.cameraOff = true; });
			} else {
				this.isLoaded = true;
				this.cameraOff = false;
			}
		},
		computed: {
			requestInput() {
				return !this.cameraOff && this.errorMessage === null;
			}
		},
		methods: {
		    nextCamera: function (){
		        if (this.camera === 0){
		            this.camera++;
		        } else if (this.camera == this.cameras.length -1) {
		            this.camera = 0;
		        } else {
		            this.camera++;
		        }
		        
		    },
			setQrData (qrData) {
				this.qrData = qrData;
				this.cameraOff = !!qrData;
			},
			retry() {
				this.cameraOff = true;
				this.$nextTick(this.reset);
			},
			reset() {
				this.setQrData(null);
				this.errorMessage = null;
				this.workload = [];
                this.decoder = null;
			},
			close() {
				if (this.modalId) {
					const modal = bootstrap.Modal.getInstance(document.getElementById(this.modalId));
					modal.hide();
				}
				this.reset();
			},
			onDecode(content) {
				if (this.qrData) return;

				if (!content.toLowerCase().startsWith("ur:")) {
					this.setQrData(content);
					this.workload = [];
				} else {
                    if (this.workload.length == 0){
                        const d = this.decoder || new window.URlib.URRegistryDecoder();
                        if (d.receivePart(content)){
                            this.decoder = d;
                            if (d.isComplete()){
                                if (!this.decoder.isSuccess()){
				                    this.errorMessage = this.decoder.resultError();
                                }else{
                                    this.setQrData(this.decoder.resultRegistryType().toString());
                                }
                            }
                        }
                        if (this.decoder != null){
                            return;
                        }
                    }
					const [index, total] = window.bcur.extractSingleWorkload(content);
					if (this.workload.length > 0) {
						const currentTotal = this.workload[0].total;
						if (total !== currentTotal) {
							this.workload = [];
						}
					}
					if (!this.workload.find(i => i.index === index)) {
						this.workload.push({
							index,
							total,
							data: content,
						});
						if (this.workload.length === total) {
							const decoded = window.bcur.decodeUR(this.workload.map(i => i.data));
							this.setQrData(decoded);
						}
					}
				}
			},
			submitData() {
				if (onDataSubmit) {
					onDataSubmit(this.qrData);
				}
				this.close();
			},
			logErrors(promise) {
				promise.catch(console.error)
			},
			paint(detectedCodes, ctx) {
				for (const detectedCode of detectedCodes) {
                    const [ firstPoint, ...otherPoints ] = detectedCode.cornerPoints
                    ctx.strokeStyle = "#51b13e";
                    ctx.beginPath();
                    ctx.moveTo(firstPoint.x, firstPoint.y);
                    for (const { x, y } of otherPoints) {
                      ctx.lineTo(x, y);
                    }
                    ctx.lineTo(firstPoint.x, firstPoint.y);
                    ctx.closePath();
                    ctx.stroke();
                }
			},
			onInit(promise) {
				promise.then(() => {
					this.errorMessage = null;
					if (app.cameras.length === 1)
                    {
                        navigator.mediaDevices.enumerateDevices().then(function (devices) {
                            for (const device of devices) {
                                if (device.kind == "videoinput"){
                                   app.cameras.push( device.deviceId)
                                }
                            }
                        });
                    }					 
				}).catch(error => {
					if (error.name === 'StreamApiNotSupportedError') {
						this.noStreamApiSupport = true;
					} else if (error.name === 'NotAllowedError') {
						this.errorMessage = 'A permission to the camera is needed to scan the QR code. Please grant the browser access and then retry.'
					} else if (error.name === 'NotFoundError') {
						this.errorMessage = 'A camera was not detected on your device.'
					} else if (error.name === 'NotSupportedError') {
						this.errorMessage = 'This page is served in non-secure context (HTTPS, localhost or file://)'
					} else if (error.name === 'NotReadableError') {
						this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
					} else if (error.name === 'OverconstrainedError') {
						this.errorMessage = 'Constraints don\'t match any installed camera.'
					} else {
						this.errorMessage = 'UNKNOWN ERROR: ' + error.message
					}
				})
			}
		}
	});
}
</script>

BTCPayServer/Views/Shared/Confirm.cshtml
@model ConfirmModel

@{
    ViewData["Title"] = Model.Title;
    Layout = "_LayoutSimple";
}

@section PageHeadContent {
    <style>
        body > .content-wrapper { display: flex; min-height: 100vh; }
        .modal-dialog .btn-close { display: none; }
    </style>
}

@section PageFootContent {
    <script>
        document.getElementById('ConfirmCancel').addEventListener('click', function () {
            history.back();
            return false;
        })
    </script>
}

<partial name="ConfirmModal" model="Model" />

BTCPayServer/Views/Shared/ConfirmModal.cshtml
@model ConfirmModel

<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="ConfirmTitle">@Model.Title</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <vc:icon symbol="close" />
            </button>
        </div>

        <div class="modal-body">
            <div id="ConfirmDescription">
                @if (Model.DescriptionHtml)
                {
                    @Safe.Raw(Model.Description)
                }
                else
                {
                    @Model.Description
                }
            </div>
        </div>

        @if (!string.IsNullOrEmpty(Model.Action))
        {
            <form id="ConfirmForm" method="post" action="@Model.ActionUrl" rel="noreferrer noopener">
                <div class="modal-body pt-0" id="ConfirmText" hidden>
                    <label for="ConfirmInput" class="form-label">Confirm the action by typing <strong id="ConfirmInputText"></strong>:</label>
                    <input id="ConfirmInput" class="form-control"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary only-for-js" data-bs-dismiss="modal" id="ConfirmCancel">Cancel</button>
                    <button type="submit" class="btn @Model.ButtonClass" id="ConfirmContinue">@Model.Action</button>
                </div>
            </form>
        }
    </div>
</div>

BTCPayServer/Views/Shared/EmailsBody.cshtml
@model BTCPayServer.Models.ServerViewModels.EmailsViewModel

<div class="row">
    <div class="col-lg-6">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h2 class="mb-0">@ViewData["Title"]</h2>
            <div class="dropdown only-for-js" id="quick-fill">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="QuickFillDropdownToggle">
                    Quick Fill
                </button>
                <div class="dropdown-menu" aria-labelledby="QuickFillDropdownToggle">
                    <a class="dropdown-item" href="" data-server="smtp.gmail.com" data-port="587">Gmail.com</a>
                    <a class="dropdown-item" href="" data-server="mail.yahoo.com" data-port="587">Yahoo.com</a>
                    <a class="dropdown-item" href="" data-server="smtp.mailgun.org" data-port="587">Mailgun</a>
                    <a class="dropdown-item" href="" data-server="smtp.office365.com" data-port="587">Office365</a>
                    <a class="dropdown-item" href="" data-server="smtp.sendgrid.net" data-port="587">SendGrid</a>
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" autocomplete="off">
    <div class="row">
        <div class="col-lg-6">
            @if (!ViewContext.ModelState.IsValid)
            {
                <div asp-validation-summary="All" class="text-danger"></div>
            }
            <div class="form-group">
                <label asp-for="Settings.Server" class="form-label"></label>
                <input asp-for="Settings.Server" data-fill="server" class="form-control"/>
                <span asp-validation-for="Settings.Server" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Port" class="form-label"></label>
                <input asp-for="Settings.Port" data-fill="port" class="form-control"/>
                <span asp-validation-for="Settings.Port" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.FromDisplay" class="form-label"></label>
                <input asp-for="Settings.FromDisplay" class="form-control"/>
                <small class="form-text text-muted">
                    Some email providers (like Gmail) don't allow you to set your display name, so this setting may not have any effect.
                </small>
                <span asp-validation-for="Settings.FromDisplay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.From" class="form-label"></label>
                <input asp-for="Settings.From" class="form-control"/>
                <span asp-validation-for="Settings.From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Settings.Login" class="form-label"></label>
                <input asp-for="Settings.Login" class="form-control"/>
                <small class="form-text text-muted">
                    For many email providers (like Gmail) your login is your email address.
                </small>
                <span asp-validation-for="Settings.Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                @if (!Model.PasswordSet)
                {

                    <label asp-for="Settings.Password" class="form-label"></label>
                    <input asp-for="Settings.Password" type="password" class="form-control"/>
                    <span asp-validation-for="Settings.Password" class="text-danger"></span>
                }
                else
                {
                    <label asp-for="Settings.Password" class="form-label"></label>
                    <div class="input-group">
                        <input value="Configured" type="text" readonly class="form-control"/>
                        <button type="submit" class="btn btn-danger" name="command" value="ResetPassword">Reset</button>
                    </div>
                }
            </div>
            <input asp-for="PasswordSet" type="hidden"/>
            <button type="submit" class="btn btn-primary" name="command" value="Save">Save</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <h4 class="mt-5 mb-3">Testing</h4>
                <p>
                    To test your settings, enter an email address below.
                </p>
                <label asp-for="TestEmail" class="form-label"></label>
                <input asp-for="TestEmail" class="form-control" />
                <span asp-validation-for="TestEmail" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-secondary mt-2" name="command" value="Test">Send Test Email</button>
        </div>
    </div>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        delegate('click', '#quick-fill .dropdown-menu a', function (e) {
            e.preventDefault();
            
            const data = e.target.dataset;
            Object.keys(data).forEach(function (key) {
                const value = data[key];
                const input = document.querySelector('input[data-fill="' + key + '"]');
                if (input) {
                    const type = input.getAttribute('type');
                    if (type === 'checkbox') {
                        input.checked = value;
                    } else {
                        input.value = value;
                    }
                }
            });
        });
    });
</script>

BTCPayServer/Views/Shared/LayoutFoot.cshtml
@addTagHelper *, BundlerMinifier.TagHelpers

<bundle name="wwwroot/bundles/bootstrap-bundle.min.js" asp-append-version="true" />
<bundle name="wwwroot/bundles/main-bundle.min.js" asp-append-version="true" />

BTCPayServer/Views/Shared/LayoutHeadTheme.cshtml
@using BTCPayServer.Abstractions.Contracts
@inject ISettingsRepository _settingsRepository
@addTagHelper *, BundlerMinifier.TagHelpers
@{ var theme = await _settingsRepository.GetTheme(); }

@if (theme.CustomTheme)
{
    <link href="@Context.Request.GetRelativePathOrAbsolute(theme.CssUri)" rel="stylesheet" asp-append-version="true" />
}
else
{
    <link href="~/main/themes/default.css" asp-append-version="true" rel="stylesheet" />
    <link href="~/main/themes/default-dark.css" asp-append-version="true" rel="stylesheet" id="DarkThemeLinkTag" />
    <script src="~/js/theme-switch.js" asp-append-version="true"></script>
    <noscript><style>.btcpay-theme-switch { display: none !important; }</style></noscript>
}

BTCPayServer/Views/Shared/NotificationEmailWarning.cshtml
<div class="alert alert-warning alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <vc:icon symbol="close" />
    </button>
    The Email settings have not been configured on this server or store yet. Setting this field will not send emails until then. <a asp-action="Emails" asp-controller="Stores" asp-route-storeId="@Model" class="alert-link">Configure store email settings</a>
</div>

BTCPayServer/Views/Shared/ShowQR.cshtml
<div id="scan-qr-modal-app">
    <div class="modal" tabindex="-1" role="dialog" :id="modalId">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{title}} <template v-if="fragments.length > 1">({{index+1}}/{{fragments.length}})</template></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <vc:icon symbol="close"/>
                    </button>
                </div>
                <div class="modal-body ">
                    <div class="qr-container text-center" style="min-height: 256px;">
                        <qrcode v-bind:value="currentFragment" :options="{ width: 256,height:256, margin: 1, color: {dark:'#000', light:'#f5f5f7'} }">
                        </qrcode>
                    </div>
                    <ul class="nav justify-content-center bg-light text-dark mt-2" v-if="allowedModes.length > 1">
                        <li class="nav-item" v-for="allowedMode in allowedModes">
                            <a class="nav-link"
                               v-bind:class="{ 'active': allowedMode == currentMode}" href="#" v-on:click="currentMode = allowedMode">
                                {{allowedMode}}
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
 function initQRShow(title, data, modalId)
 {
 	return new Vue(
 	{
 		el: '#scan-qr-modal-app',
 		components:
 		{
 			qrcode: VueQrcode
 		},
 		data:
 		{
 			index: -1,
 			title: title,
 			speed: 500,
 			data: data,
 			fragments: [],
 			active: false,
 			modalId: modalId,
 			currentMode: "bcur",
 			allowedModes: ["static","bcur"]
 		},
 		computed:
 		{
 			currentFragment: function ()
 			{
 				return this.fragments[this.index];
 			}
 		},
 		mounted: function ()
 		{
 			var self = this;
 			$("#" + this.modalId)
 				.on("shown.bs.modal", function ()
 				{
 					self.start();
 				})
 				.on("hide.bs.modal", function ()
 				{
 					self.active = false;
 				});
 			self.setFragments();
 		},
 		watch:
 		{
 		    currentMode: function(){
 				this.setFragments();
 		    },
 			data: function ()
 			{
 				this.setFragments();
 			}
 		},
 		methods:
 		{
 			setFragments: function ()
 			{
 				if (!this.data)
 				{
 					this.fragments = [];
 					return;
 				}
 				if (this.currentMode == "bcur"){
 				    this.fragments = window.bcur.encodeUR(this.data.toString(), 200);
 				}else{
 				    this.fragments = [this.data.toString()];
 				}
 			},
 			start: function ()
 			{
 				this.active = true;
 				this.index = -1;
 				this.playNext();
 			},
 			playNext: function ()
 			{
 				if (!this.active)
 				{
 					return;
 				}
 				this.index++;
 				if (this.index > (this.fragments.length - 1))
 				{
 					this.index = 0;
 				}
 				setTimeout(this.playNext, this.speed)
 			}
 		}
 	});
 }
 </script>